laminlabs/lamindb-setup

lndb/_migrate/deploy.py
Whenever no actual migration is performed, don't ask for a migration.
=> 🚸 New migration deployment logic that also factors in migration ids

docs/faq/test-sqlite-sync.ipynb, lamindb_setup/_close.py, lamindb_setup/_delete.py, lamindb_setup/_init_instance.py, lamindb_setup/_load_instance.py, lamindb_setup/dev/_django.py, lamindb_setup/dev/_exclusion.py, lamindb_setup/dev/_settings_instance.py
By having only 3 points in which we synch & lock/unlock the remote SQLite file, we can simplify the code dramatically and still create a safe & performant user experience.
The one and only downside is that the user needs to manually push changes back to the cloud by calling `lamin close`. But given this is a known journey (`git push`), it shouldn't be a big deal.
The 3 points are:
* `init` merely locks the remote sqlite file but doesn't yet upload it
* `load` synchs changes from a remote sqlite file to the local file & locks the remote file
* `close` updates the remote sqlite file & unlocks it
In this PR, we don't put forward the locking on init because it is heavily used in concurrent CI settings.
The really great thing here is that `lamindb` can be entirely free from logic around …
=> 🚸 Simplify remote SQLite synching & locking

lamindb_setup/_load_instance.py, lamindb_setup/dev/_cloud_sqlite_locker.py, lamindb_setup/dev/_settings_instance.py
Now 
`settings.instance.cloud_sqlite_locker.lock()` doesn't lock anything by itself, it just check if it can obtain write access to the (cloud sqlite) instance.
After calling `settings.instance.cloud_sqlite_locker.lock()` at the load of an instance (internally), all write operations in lamindb should check the property `settings.instance.cloud_sqlite_locker.has_lock` before proceeding. 
upd:
Now prevents an instance from loading completely if locked by another user.
=> 🔥 Adapt locker to lock entire lamindb session

lamindb_setup/_init_instance.py
There was no lock on `init`, this is a bug.
=> 🐛 Lock cloud sqlite instances on init

lamindb_setup/dev/__init__.py, lamindb_setup/dev/_django.py
New warning:
```
% lamin load testdb
💡 found cached instance metadata: /Users/falexwolf/.lamin/instance--testuser1--testdb.env
🔶 
Your database is not up to date with your installed Python library.
The database misses the following migrations:
[<Migration lnschema_core.0014_rename_ref_field_featureset_registry>, <Migration lnschema_core.0015_file_initial_version_file_version>]
Only if you are an admin and manage migrations manually, deploy them to the database:
lamin migrate deploy
Otherwise, downgrade your Python library to match the database!
✅ loaded instance: testuser1/testdb
```
=> 🚸 Reformat missing-migrations warning

lamindb_setup/dev/_storage.py, tests/test_load_persistent_instance.py
Needed in `lamindb` for `File` etc.
=> ✨ A function to convert pathlike to Path or UPath inheriting options from root

lamindb_setup/_init_instance.py, lamindb_setup/dev/_settings_storage.py, lamindb_setup/dev/upath.py, tests/test_load_persistent_instance.py
- https://github.com/laminlabs/lamindb/pull/1072
This is likely not the ultimate solution, but should be good for a while.
It's hard to subclass UPath.
I think it's also overkill to create a global `Permissions` class at this point.
Essentially, it's as simple as checking whether AWS credentials are present, and that's happening now.
We could extend this to GCP & Azure if needed at some point.
=> ♻️ Introduce `create_path`

lamindb_setup/_init_instance.py, lamindb_setup/_load_instance.py, lamindb_setup/dev/_settings_instance.py
Make `_update_local_sqlite_file` and `_update_cloud_sqlite_file` consistent for optional locking and unlocking, avoid unneeded unlockin on instance init.
=> ♻️ Refactor optional cloud sqlite locking and unlocking

lamindb_setup/dev/django.py
Now the instance is unlocked on `lamin migrate deploy`, logically it should not happen.
=> 🐛 Do not unlock cloud sqlite instance on migrate deploy

lamindb_setup/_cache.py, lamindb_setup/dev/_settings_storage.py
=> 🐛 Use shutil.move to move the sqlite file when changing cache folder

lamindb_setup/dev/_hub_client.py, lamindb_setup/dev/_hub_core.py, lamindb_setup/dev/_settings_storage.py, lamindb_setup/dev/upath.py
For https://github.com/laminlabs/lamindb/pull/1454
=> ♻️ Allow passing `access_token` directly

.github/workflows/build.yml, lamindb_setup/core/hashing.py, lamindb_setup/core/upath.py, tests/test_hashing.py
- https://github.com/laminlabs/lamindb/pull/1476
- https://www.notion.so/laminlabs/Monitor-hosted-storage-usage-enable-safe-deletes-4afbd336989c4f578fc8fab2194328eb
=> ♻️ Move generic hashing and storage utilities from `lamindb` into `lamindb-setup`

docs/hub-prod/test-insufficient-user-info.ipynb, lamindb_setup/_setup_user.py
Several old `RuntimeError` instances are now `SystemExit` and have an error emoji.
Now:
```
% lamin login alex
✗ Use your email for your first login in a compute environment. After that, you can use your handle.
```
Previously:
```
% lamin login alex
❗ using anonymous user (to identify, call: lamin login)
Traceback (most recent call last):
File "/Users/falexwolf/miniconda3/envs/py310/bin/lamin", line 8, in <module>
sys.exit(main())
File "/Users/falexwolf/miniconda3/envs/py310/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/Users/falexwolf/miniconda3/envs/py310/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
rv = self.invoke(ctx)
File "/Users/falexwolf/miniconda3/envs/py310/lib/python3.10/site-packages/ …
```
=> 🔊 Do not show traceback for basic login errors

.github/workflows/build.yml, lamindb_setup/core/_hub_core.py, lamindb_setup/core/_settings_save.py, lamindb_setup/core/_settings_store.py, tests/hub-local/test_all.py, tests/hub-local/test_update_schema_in_hub.py
https://github.com/laminlabs/laminhub/pull/1209
=> ✨ Load instance settings with edge function

.github/workflows/build.yml, lamindb_setup/core/_hub_core.py, tests/hub-local/test_all.py
=> ✅ Test connect_instance_new for anonymous

lamindb_setup/_connect_instance.py
Needs this https://github.com/laminlabs/laminhub/pull/1248 deployed
=> ✅ Use connect_instance_new for Koncopd, sunnyosun and falexwolf for local testing

lamindb_setup/_connect_instance.py, lamindb_setup/_init_instance.py, lamindb_setup/_schema_metadata.py, lamindb_setup/core/_hub_core.py, lamindb_setup/core/_settings_instance.py, lamindb_setup/core/_settings_storage.py, lamindb_setup/core/cloud_sqlite_locker.py, tests/hub-cloud/scripts/script-init-pass-user-no-writes.py, tests/hub-cloud/test_init_pass_user_no_writes.py
https://github.com/laminlabs/laminhub/issues/1271
This moves all internal utility arguments to `kwargs` in `lamindb_setup.connect`.
Adds 2 additional arguments: `_user` and `_write_settings`.
1. `_user` allows to pass user settings (with `access_token`) to `connect` and they are used instead of `lamindb_setup.settings.user`.
2. `_write_settings` when set to `False` forces `connect` not to write any settings env files. It is set to `True` by default for now.
I believe this addresses point 1-2 in the linked issue.
=> ♻️ Overhaul `init` for more convenient use in laminhub

docs/hub-cloud/02-connect-local-instance.ipynb, lamindb_setup/_connect_instance.py, lamindb_setup/_init_instance.py, tests/hub-cloud/test_connect_instance.py, tests/storage/test_storage_access.py
Closes https://github.com/laminlabs/lamindb-setup/issues/862
This eliminates `storage` completely and moves `db` to `kwargs` `_db`, because passing db string is still needed for internal use.
=> ♻️ Simplify connect by eliminating db and storage arguments

lamindb_setup/core/_hub_client.py, lamindb_setup/core/_hub_core.py
Propagate the changes in:
- https://github.com/laminlabs/laminhub/pull/1342
=> 🚚 Rename hub edge functions

lamindb_setup/_connect_instance.py, lamindb_setup/_migrate.py, lamindb_setup/core/_hub_core.py
- https://github.com/laminlabs/lamindb/issues/1990
=> 🚸 Warn about inconsistent lamindb versions during `connect_hub`

docs/hub-prod/test-cloud-sync.ipynb, lamindb_setup/_delete.py, lamindb_setup/core/_settings_storage.py, pyproject.toml
Fix https://github.com/laminlabs/lamindb-setup/issues/868
=> 🐛 Fix cache paths

lamindb_setup/_init_instance.py, lamindb_setup/core/django.py, noxfile.py
If you don't have a schema module installed, you'll not see the metadata from its registries.
For example, in an environment that lacks `findrefs`:
```python
>>> import lamindb as ln
! schema module 'findrefs' is not installed → no access to its registries (resolve via `pip install findrefs`)
→ connected lamindb: laminlabs/lamin-dev
>>> artifact = ln.Artifact.get("iw9RRhFApeJVHC1L0001")
>>> artifact.describe()
Artifact(uid='iw9RRhFApeJVHC1L0001', version='1.0', is_latest=True, description='my RNA-seq', suffix='.parquet', type='dataset', size=4091, hash='pYYPTWIvnIZ83a9_0WLNYg', _hash_type='md5', _accessor='DataFrame', visibility=1, _key_is_virtual=True, created_at=2024-09-02 14:15:10 UTC)
Provenance
.storage = 's3://lamin-eu-central-1/9fm7UN13'
.transform = 'Introduction'
.run = …
```
=> 🚸 Do not error if a schema module of an instance isn't installed

lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_storage.py
Now `cloud_to_local` can (and should) be called `lamindb_setup.settings.paths.cloud_to_local`.
https://github.com/laminlabs/lamindb-setup/issues/863
=> ♻️ Move cloud_to_local to lnamindb_setup.settings

lamindb_setup/core/_aws_credentials.py, tests/hub-prod/test_aws_credentials_manager.py
Re https://github.com/laminlabs/pfizer-lamin-usage/issues/54 https://github.com/laminlabs/pfizer-lamin-usage/issues/55
This checks if aws credentials are able to resolve `head_bucket` on a test bucket (lamindata) and if not then sets anon=True for a specified list of public buckets.
This checks with `head_bucket` only once on init.
=> ✨ Set anon for specified public s3 buckets if aws credentials fail

lamindb_setup/core/upath.py
I have realized that this doesn't really work:
`isinstance(Path("."), LocalPathClasses) # gives False, we expected True`
because `PosixPath` is a superclass of `PosixUPath`, not the other way around.
Now this will work as expected. 
`isinstance(Path("."), LocalPathClasses) # True`
`isinstance(PosixUPath("."), LocalPathClasses) # True`
=> 🐛 Correct local path check

noxfile.py
Sometimes, during releases, it reinstalls `lamin-cli` to older versions for some reason.
=> 💚 Fix CI build

docs/hub-prod/test-cloud-sync.ipynb, lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_storage.py, lamindb_setup/core/upath.py, tests/hub-local/test_all.py
Needed to allow synchronization for http links.
=> ✨ Allow to synchronize via st_size if st_mtime is not present in UPath.stat()

lamindb_setup/core/_hub_core.py, lamindb_setup/core/_hub_crud.py
Always search default storage through the storage table.
=> 🐛 Prepare for deletion of the storage_id column from the instance table

lamindb_setup/_init_instance.py, lamindb_setup/core/_hub_crud.py, lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_instance.py, tests/hub-cloud/test_init_instance.py
Fix https://github.com/laminlabs/lamindb/issues/2180
Also fix incorrect tests in test_init_instance.py
=> 🐛 Fix init instance tests and add init of a local instance in cwd

lamindb_setup/core/upath.py
Compensate for https://github.com/fsspec/filesystem_spec/issues/1766
=> 🐛 Fix double download of files in http

docs/hub-cloud/01-init-local-instance.ipynb, docs/hub-cloud/03-add-managed-storage.ipynb, docs/hub-cloud/08-test-multi-session.ipynb, docs/hub-prod/test-connect-anonymously.ipynb, lamindb_setup/_check_setup.py, lamindb_setup/_connect_instance.py, lamindb_setup/_django.py, lamindb_setup/_exportdb.py, lamindb_setup/_init_instance.py, lamindb_setup/_migrate.py, lamindb_setup/_schema_metadata.py, lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_instance.py, lamindb_setup/core/_settings_storage.py, lamindb_setup/core/_settings_user.py, lamindb_setup/core/django.py, lamindb_setup/core/upath.py, noxfile.py, pyproject.toml, tests/hub-cloud/scripts/script-to-fail-managed-storage.py, tests/hub-cloud/test_connect_instance.py, tests/hub-local/test_update_schema_in_hub.py, tests/hub-prod/test_django.py
See:
- https://github.com/laminlabs/lamindb/pull/2309
=> 🏗️ Integrate `lnschema-core` into `lamindb`

.pre-commit-config.yaml, docs/hub-cloud/01-init-local-instance.ipynb, docs/hub-cloud/02-connect-local-instance.ipynb, docs/hub-cloud/03-add-managed-storage.ipynb, docs/hub-cloud/05-init-hosted-instance.ipynb, docs/hub-cloud/06-connect-hosted-instance.ipynb, docs/hub-cloud/07-keep-artifacts-local.ipynb, docs/hub-prod/test-cloud-sync.ipynb, docs/hub-prod/test-sqlite-lock.ipynb, lamindb_setup/core/upath.py, pyproject.toml
Fixes #928 
- Now suppresses the traceback of not very useful CLI delegation (click) when the `InstanceNotEmpty` exception is raised
- Upgrades Ruff to the latest version
=> 🎨 Simplify InstanceNotEmpty UX

lamindb_setup/__init__.py
Fixes https://github.com/laminlabs/lamindb/issues/1851
- Now checking for more common CI environment variables to disable the `NotebookNotSaved` error from `ln.finish()`
- Since we're using Github Actions we could now probably get rid of `LAMIN_TESTING` but one step at a time
=> ✨ Check for more CI environments

lamindb_setup/_migrate.py
Now throws an error:
```
% lamin migrate deploy                
❌ You're in auto-connect mode, please run: lamin settings auto-connect false
```
This likely wasn't necessary before we removed lnschema-core.
=> 🚸 Error on auto-connect

lamindb_setup/_connect_instance.py, lamindb_setup/_migrate.py, tests/hub-cloud/test_connect_instance.py
Addresses:
- https://github.com/laminlabs/lamindb-setup/issues/948
Also improves the migration dialogue when instance version and package version mismatch.
=> 🚸 Accept `None` in `connect()` and improve migration dialogue

lamindb_setup/_connect_instance.py, lamindb_setup/core/_settings_instance.py
Migration was done without properly updating cloud sqlite file.
Related to https://github.com/laminlabs/lamindb/issues/2356
Also in case the sqlite file is not in the cloud, the migration was creating an empty sqlite file that was confusing the connection process futher.
=> 🐛 Fix migration for cloud sqlite instances

docs/hub-cloud/01-init-local-instance.ipynb, docs/hub-cloud/02-connect-local-instance.ipynb, lamindb_setup/_check_setup.py, lamindb_setup/_connect_instance.py, lamindb_setup/_migrate.py, lamindb_setup/core/_settings_instance.py
And raise `RuntimeError` if it is not there.
=> 🥅 Check instance.modules when loading a lamindb schema module

lamindb_setup/core/_settings_instance.py
Fixes #954 
Before:
```
! none of the registered local storage locations were found in your environment: <QuerySet [Storage(uid='SOMEID', root='/data/path', type='local', instance_uid='SOMEID', created_by_id=6, space_id=1, created_at=2024-07-26 13:14:05 UTC), Storage(uid='SOMEID', root='/data/path2', type='local', instance_uid='SOMEID', created_by_id=4, space_id=1, created_at=2024-06-19 12:52:20 UTC),....THIS CONTINUES FOR A WHOLE PAGE SO THAT MY TERMINAL WAS COMPLETELY FLOODED
```
After:
```
lukas@lukas ~/c/lamindb-setup (main)> lamin connect customer/instance
! none of the registered local storage locations were found:
/data/specific/path
/data/specific/path2
/data/specific/path3
/data/specific/path4
/data/specific/path5
/data/specific/path6
→ please register a new local storage …
```
=> ✨ Improve local storage not found warning message

.gitignore, docs/hub-cloud/01-init-local-instance.ipynb, docs/hub-cloud/02-connect-local-instance.ipynb, docs/hub-cloud/07-keep-artifacts-local.ipynb, docs/hub-prod/test-empty-init.ipynb, lamindb_setup/_delete.py, lamindb_setup/core/_settings_instance.py, lamindb_setup/core/_settings_storage.py, lamindb_setup/core/upath.py, tests/hub-cloud/test_init_instance.py
```
mydirectory % tree -a 
.
├── .lamindb
│   └── _is_initialized
└── a1471417fc7c5ae99546d2bd8ef2c28d.lndb
2 directories, 2 files
```
```
mydirectory % tree -a 
.
└── .lamindb
└── _is_initialized
└── _lamin.db
2 directories, 2 files
```
Iterates on:
- https://github.com/laminlabs/lamindb-setup/pull/600
=> ♻️ Move the lamindb SQLite file into the `.lamindb/` folder

lamindb_setup/core/_settings_storage.py
Fixes repetitive writes of `_is_initialized` on `ln.Artifact`  initialization with a cloud storage not in `ln.Storage` table.
`init_storage` is called inside `Artifact` [here](https://github.com/laminlabs/lamindb/blob/01abda450218a9647b1f23b5368193425a0fcf7a/lamindb/models/artifact.py#L180).
=> 🐛 Only call `mark_storage_root` to check write access if the storage record has been just created

lamindb_setup/core/_hub_core.py, pyproject.toml
The new version of `gotrue` doesn't have `_decode_jwt` anymore.
=> 🐛 Use pyjwt to decode access_token

lamindb_setup/core/_settings_instance.py
Should have been fixed a long time ago. 😔
=> 🐛 Return an empty set not a dict for modules

lamindb_setup/core/_hub_core.py
It is `uid` in `Storage`, not `lnid`.
=> 🐛 Correct field name in `_select_storage_or_parent`

lamindb_setup/core/_settings_store.py
It is not always needed, especially with connecting on initializing with `_write_settings=False`.
=> 🩹 Catch exceptions on creating lamin settings directory

lamindb_setup/_connect_instance.py
Also don't ignore `LAMINDB_DJANGO_DATABASE_URL` env variable in `migrate_lnschema_core`.
=> 🩹 `_db` in `connect` now takes full precedence over hub and locally stored connections

lamindb_setup/core/_settings.py
Important to prevent failures on read-only systems like aws lambda
=> 🥅 Do not fail if can not create cache dir

.github/workflows/build.yml, docs/hub-cloud/01-init-local-instance.ipynb, docs/hub-cloud/07-keep-artifacts-local.ipynb, docs/hub-cloud/08-test-multi-session.ipynb, docs/hub-cloud/09-test-init-paths.ipynb, lamindb_setup/core/_settings_storage.py, lamindb_setup/core/upath.py
`create_path` now expands the user directory by default to support `"~"` characters. Since it uses `UPath`, this has no effect on remote paths. They are returned unchanged. I could have made that change in the `process_data` function of `Artifact` at `path = create_path(data, access_token=access_token)` but I think it fits a bit better here. No strong feelings.
Before | After
--- | ---
This now also works for `init` where we support user directories
=> ✨ Expand user directory by default

lamindb_setup/__init__.py, lamindb_setup/_connect_instance.py, lamindb_setup/_init_instance.py
1. Always show "connected ..." logging message.
2. Disable updating the user on fine grained instances for now.
=> 🩹 Various fixes for `connect`

lamindb_setup/core/_hub_core.py, tests/hub-local/scripts/script-connect-fine-grained-access.py
This is needed for local tests in `laminhub`.
=> ✨ Allow to specify a db token via the env variable `LAMIN_TEST_DB_TOKEN`

docs/hub-prod/test-cache-management.ipynb, lamindb_setup/_cache.py, lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_load.py, lamindb_setup/core/_settings_save.py, lamindb_setup/core/_settings_store.py, pyproject.toml
Address https://github.com/laminlabs/pfizer-lamin-usage/issues/255
This allows to specify system wide configuration (only cache path for now) via `system.env` file in 
```python
platformdirs.site_config_dir(appname="lamindb", appauthor="laminlabs")
```
Specific folder is system-dependent and is shown in the output of `lamin info`.
Example of `system.env` file:
```
lamindb_cache_path=path/to/cache
```
The user specified cache path will take precedence this .
=> ✨ Allow to specify system-wide cache path

lamindb_setup/core/_settings_storage.py, lamindb_setup/core/upath.py, tests/storage/test_storage_stats.py, tests/storage/test_to_url.py
Now (monkey-patched) `upath.to_url()` fails if `head_bucket` is not permitted, this PR fixes the problem.
Also there was a bug in `upath.to_url()` for hosted buckets.
=> 🐛 Rework `get_storage_region()` to make it reliable and use it in `upath.to_url()` 

lamindb_setup/_connect_instance.py
Change the logic of determining the correct db connection.
- Always use hub db connection over local if it is present.
- Do not error if hub db connection string is different from the local connection string, just use hub.
=> 👔 Rework `update_db_using_local` to always use hub db connection if available

docs/hub-cloud/08-test-multi-session.ipynb, lamindb_setup/_cache.py, lamindb_setup/_check_setup.py, lamindb_setup/_connect_instance.py, lamindb_setup/_init_instance.py, lamindb_setup/core/_settings.py, lamindb_setup/core/_settings_instance.py, lamindb_setup/core/_settings_load.py, lamindb_setup/core/django.py, lamindb_setup/errors.py, tests/hub-cloud/scripts/script-to-fail-managed-storage.py, tests/hub-cloud/test_connect_instance.py
The change here should allow us to eliminate the conditional import in the lamindb root module.
- https://github.com/laminlabs/lamindb/pull/2851
This PR fixes several issues with the reset logic introduced here:
- https://github.com/laminlabs/lamindb-setup/pull/1046
Stale class issue: https://claude.ai/share/b4b3dcb5-4685-42dc-8e32-50851d41c5ac
=> 🚸 Set up Django on every import of lamindb via a "mock instance"

lamindb_setup/_init_instance.py, lamindb_setup/_register_instance.py, lamindb_setup/_set_managed_storage.py, lamindb_setup/core/_hub_core.py, lamindb_setup/core/_settings_instance.py, lamindb_setup/core/_settings_storage.py, noxfile.py, tests/hub-cloud/test_init_instance.py, tests/hub-local/test_all.py
This PR simplifies `init_storage()` and related parts of the code.
The main reason for why simplification is possible is because the order of creation of hub instance and storage records can be reverted; the previous order still dates back to the originally inverted foreign key relationships between instance and storage in the hub.
This will also marginally speed up instance creation (one network request less).
The PR prepares passing a `space_id` argument to `init_storage_hub()`, which will be natural and parallel to how `instance_id` is now handled. Prior to this PR, due to the complicated order, several conditionals had to be met. Now, `instance_id` is always passed when creating a storage record on the hub.
Comes with:
- https://github.com/laminlabs/lamindb/pull/3023
=> ♻️ Simplify `init_storage()`

lamindb_setup/core/_hub_core.py, lamindb_setup/core/_settings_storage.py
I want to keep dealing with spaces as simple as possible in lamindb.
The simplest way would be to not even store the space association of a storage location in the hub db, but just in the instance db. But we have the storage and space tables in the hub db already it'd seem like a departure from the idea of keeping track of key metadata in the hub db.
Hence, this PR merely enables populating the space table in the hub db.
Notion page: https://www.notion.so/laminlabs/Enable-fine-grained-access-management-for-the-storage-layer-2392aeaa55e180ed85f8dd21cff41c70
=> ✨ Add `space_uuid` argument to `init_storage()`

lamindb_setup/core/django.py
Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/358
So it will timeout after trying to connect to a postgres db  for 20 sec.
=> 🔧 Set `connect_timeout` for postgres

lamindb_setup/core/django.py
Avoid 
`OperationalError: connection to server at "aws-0-us-east-1.pooler.supabase.com" (44.216.29.125), port 6543 failed: received invalid response to GSSAPI negotiation: S`
=> 🗃️ Disable `gssencmode` for postgres

lamindb_setup/_migrate.py
This is now necessary because we dropped the `schema_id` arg from the hub REST API.
=> 🏗️ Invalidate instance cache after migration

lamindb_setup/_migrate.py, lamindb_setup/core/_aws_storage.py, lamindb_setup/core/_hub_client.py, lamindb_setup/core/_hub_core.py, pyproject.toml
I realize now that before it was ignoring read timeouts completely.
=> 🐛  Use `httpx_retries` to retry on all timeouts and connection errors for http requests
