laminlabs/lamindb-setup

.pre-commit-config.yaml
docs/guide/04-set-storage.ipynb
lndb/_set.py
lndb/dev/_storage.py
pyproject.toml

✨ Allow to set additional fsspec kwargs for cloud instances

---

tests/test_notebooks.py

🔊 Use lamin_logger in test_notebooks.py

---

docs/guide/migrate.md

📝 Improve migration docs

---

lndb/__main__.py
lndb/_notebook.py

`lndb track nb.ipynb --pypackage lamindb,bionty --parent parent_id`
The command initializes nbproject metadata in `nb.ipynb` to avoid writing it in `ln.track()`
It doesn't create `Transform` or `Run`, i think it is better to do from the notebook itself.

✨ Add track command to CLI

---

lndb/_migrate/deploy.py
lndb/dev/_setup_schema.py
pyproject.toml

- https://github.com/laminlabs/lndb/pull/380

:fire: Remove schema modules logic from setup_schema

---

lamindb_setup/_notebook.py

✨ New id and version in track

---

docs/guide/04-set-storage.ipynb
docs/guide/05-schema-modules.ipynb
lamindb_setup/__init__.py
lamindb_setup/_check_instance_setup.py
lamindb_setup/_init_instance.py
lamindb_setup/dev/_settings_instance.py
lamindb_setup/dev/_setup_schema.py
lamindb_setup/dev/_storage.py
lamindb_setup/test/_env.py
lamindb_setup/test/_nox.py
lamindb_setup/test/nox.py
tests/test_bionty.py

- https://github.com/laminlabs/lnschema-core/pull/181

🔥 Delete SQLAlchemy related content

---

lamindb_setup/_init_instance.py
lamindb_setup/_load_instance.py
lamindb_setup/dev/_django.py
lamindb_setup/dev/_setup_knowledge.py

Dependent on: https://github.com/laminlabs/lamindb/pull/723

:sparkles: Setup bionty version tables

---

lamindb_setup/dev/_django.py

- https://github.com/laminlabs/lnschema-core/pull/199

🍱 Added migration script from legacy instances

---

lamindb_setup/_migrate.py
tests/test_load_instance.py
tests/test_migrate.py

I don't understand why coverage doesn't pick up the test :(

✨ Add ability to check for migrations

---

docs/guide/03-set-storage.ipynb
lamindb_setup/_set.py
lamindb_setup/dev/_hub_utils.py
pyproject.toml

✨ Set s3 region in set.storage

---

lamindb_setup/_load_instance.py

Just warn when this situation arises.

🐛 Fix sqlite file not existing in the bucket error

---

lamindb_setup/_check_instance_setup.py

As it requires lamindb, it's tested in lamindb.
- https://github.com/laminlabs/lamindb/pull/852

🚸 Import order of schema modules shouldn't matter

---

lamindb_setup/dev/_cloud_sqlite_locker.py

🔒️ Increase locker expiration time to 1 week

---

lamindb_setup/__main__.py

Show help by default and add --version

---

lamindb_setup/dev/_storage.py
lamindb_setup/dev/upath.py

Needed for download progress bars

✨ Propagate kwargs through synchronization functions

---

lamindb_setup/dev/_hub_utils.py
lamindb_setup/dev/_storage.py

🐛 Fix aws access with no credentials

---

lamindb_setup/_close.py
tests/test_load_persistent_instance.py

🐛 Fix and test close for read only buckets

---

.github/workflows/build.yml
docs/faq/multi-session.ipynb
docs/faq/switch-environment.ipynb
docs/faq/test-sqlite-sync.ipynb
docs/guide/02-load-instance.ipynb
docs/guide/03-set-storage.ipynb
docs/guide/04-schema-modules.ipynb
lamindb_setup/__main__.py

Fixes https://github.com/laminlabs/lamindb-setup/issues/295

🚸 Add delete confirmation dialogue

---

docs/faq/index.md
docs/faq/test-empty-init.ipynb
lamindb_setup/dev/_storage.py
lamindb_setup/dev/upath.py
tests/unit/test_init_instance.py

🐛 Fix init in an empty s3 bucket

---

.github/workflows/build.yml
noxfile.py
pyproject.toml
tests/unit/test_init_instance.py

- https://laminlabs.slack.com/archives/C04A0RMA0SC/p1692449615305299

👷 Fix coverage compute

---

lamindb_setup/dev/_storage.py
tests/test_load_persistent_instance.py

🐛 Fix UPath check on Storage init

---

lamindb_setup/dev/_hub_client.py
tests/hub/test_runs_locally.py

- https://github.com/laminlabs/laminhub-rest/pull/259

♻️ Refactor hub client

---

docs/notebooks.md
docs/prod-only/test-load-lock.ipynb
lamindb_setup/_load_instance.py
lamindb_setup/dev/_hub_crud.py
tests/prod-only/test_hub_utils.py

🔊 Show more info about the locking user

---

lamindb_setup/dev/_hub_core.py

- https://github.com/laminlabs/lamindb-benchmarks/pull/26
- https://laminlabs.slack.com/archives/C04TMJPNCBS/p1694604322269469

🎨 Streamline login

---

docs/prod-only/test-load-lock.ipynb
lamindb_setup/_close.py
lamindb_setup/_load_instance.py
lamindb_setup/dev/cloud_sqlite_locker.py

🐛 Unlock load on error

---

docs/prod-only/test-load-lock.ipynb
lamindb_setup/_load_instance.py
lamindb_setup/dev/cloud_sqlite_locker.py

🔐 Change lock expiration time to 1 day

---

docs/prod-only/test-sqlite-sync.ipynb
lamindb_setup/_init_instance.py
lamindb_setup/_load_instance.py
lamindb_setup/dev/_settings_instance.py
lamindb_setup/dev/cloud_sqlite_locker.py

- https://github.com/laminlabs/lamindb-setup/issues/529

♻️ Refactor lock

---

lamindb_setup/dev/_settings_instance.py

To enable:
- https://github.com/laminlabs/laminapp-rest/pull/103

♻️ Do not lock instance on load for laminapp-admin

---

docs/notebooks.md
docs/prod-only/test-cache-management.ipynb
lamindb_setup/__main__.py
lamindb_setup/_cache.py
lamindb_setup/dev/_settings_save.py
lamindb_setup/dev/_settings_storage.py
lamindb_setup/dev/_settings_store.py

✨ Cache management

---

lamindb_setup/dev/_setup_bionty_sources.py

Needs https://github.com/laminlabs/bionty/pull/523

🎨 Set bionty versionsdir according to settings_dir

---

lamindb_setup/dev/upath.py

- https://github.com/laminlabs/lamindb/pull/1288

🚚 Move `view_tree` from lamindb here

---

lamindb_setup/_migrate.py
lamindb_setup/dev/django.py

🔧 Detect both missing and ahead migrations

---

lamindb_setup/dev/_settings_storage.py

✨ Set cache via LAMIN_CACHE_DIR env variable

---

lamindb_setup/dev/_settings_instance.py
lamindb_setup/dev/upath.py

subj
Fixes some issues from https://github.com/laminlabs/lamindb-setup/pull/587

🔊 Do not print progress by default

---

.github/workflows/build.yml
lamindb_setup/_init_instance.py
lamindb_setup/dev/_settings_storage.py
noxfile.py
tests/prod-staging/test_load_instance.py
tests/test_storage_access.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1701165598355019

♻️ Defer storage API access to actual access

---

lamindb_setup/dev/_settings_instance.py
lamindb_setup/dev/upath.py

🔊 Warn on sync of non-existing paths

---

docs/prod-only/test-empty-init.ipynb
docs/prod-staging/01-init-instance.ipynb
docs/prod-staging/02-load-instance.ipynb
docs/prod-staging/03-set-storage.ipynb
lamindb_setup/_init_instance.py
lamindb_setup/_load_instance.py
lamindb_setup/_register_instance.py
lamindb_setup/dev/_hub_core.py
lamindb_setup/dev/_settings_instance.py
lamindb_setup/dev/_settings_load.py
tests/hub-local/test_all.py
tests/prod-staging/test_init_instance.py
tests/prod-staging/test_load_instance.py

https://laminlabs.slack.com/archives/C03Q5TXF797/p1703186278512459

🎨 Name `.lndb` files by instance id

---

lamindb_setup/dev/_hub_crud.py
pyproject.toml
tests/test_storage_access.py

This makes the instance load operation more resilient by adding a fallback mechanism in case we change the FK constraint.

🚚 Prepare a potential migration of the hub to Django

---

lamindb_setup/dev/upath.py
tests/prod-only/test_upath.py

🐛 Fix option inheritance in create_path and add tests

---

lamindb_setup/dev/upath.py

`view_tree` is only being used as a method for the `Path` (and `UPath`) classes. There aren't any places where its being called with a `str` argument.
I've modified it to not accept `str` arguments anymore and removed the call to `create_path`.
This fixes https://github.com/laminlabs/lamindb/issues/1407

🎨 Remove call to `create_path` inside `path.view_tree`

---

docs/prod-only/test-cache-management.ipynb
docs/prod-only/test-empty-init.ipynb
docs/prod-only/test-load-lock.ipynb
docs/prod-only/test-sqlite-sync.ipynb
docs/prod-staging/01-init-instance.ipynb
docs/prod-staging/03-set-storage.ipynb
tests/hub-local/test_all.py
tests/prod-only/test_upath.py
tests/prod-staging/test_init_instance.py
tests/prod-staging/test_load_instance.py
tests/test_storage_access.py

https://laminlabs.slack.com/archives/C04TMJPNCBS/p1706266454001749

🎨 Move default storages to folders

---

.pre-commit-config.yaml
lamindb_setup/_check_instance_setup.py
lamindb_setup/_init_instance.py
lamindb_setup/dev/_settings_save.py
lamindb_setup/dev/_settings_storage.py
lamindb_setup/dev/cloud_sqlite_locker.py

This fixes the permission error and also circumvents the need for CreateBucket permission for Locker.

🐛 Fix permission error for init of hosted instances

---

docs/prod-staging/02-init-hosted-instance.ipynb
lamindb_setup/_init_instance.py
lamindb_setup/dev/_hub_core.py
lamindb_setup/dev/upath.py
tests/test_storage_access.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1706897425702599?thread_ts=1706743094.933629&cid=C04FPE8V01W

♻️ Low-latency storage permission management

---

lamindb_setup/dev/upath.py

♻️ Check manual credentials in path.fs, actually reuse anon

---

lamindb_setup/_load_instance.py

✏️ pre-commit on all files

---

lamindb_setup/dev/_hub_core.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1708174912593829

🐛 Fix aws_access calls in CLI

---

lamindb_setup/dev/cloud_sqlite_locker.py
lamindb_setup/dev/upath.py

✨ Add create_mapper util

---

lamindb_setup/dev/_settings_storage.py

🩹 Resolve cache_dir in the setter

---

lamindb_setup/_close.py
lamindb_setup/_delete.py
lamindb_setup/_init_instance.py
lamindb_setup/_load_instance.py
lamindb_setup/_migrate.py
lamindb_setup/core/_settings_instance.py

- https://laminlabs.slack.com/archives/C04FPE8V01W/p1709711289238559

♻️ Replace `InstanceSettings.identifier` with `InstanceSettings.slug`

---

lamindb_setup/core/_hub_client.py

- https://github.com/laminlabs/laminapp-ui/issues/530

♻️ Enable easy switching between prod-test and staging-test

---

docs/hub-prod/test-connect-anonymously.ipynb
lamindb_setup/core/_settings_save.py

🐛 Use root_as_str for lazy load to save settings

---

docs/hub-prod/test-cloud-sync.ipynb
docs/hub-prod/test-sqlite-sync.ipynb
docs/notebooks.md
lamindb_setup/core/cloud_sqlite_locker.py
lamindb_setup/core/upath.py
pyproject.toml

✨ Rework synchronize, support directories

---

.github/workflows/build.yml
lamindb_setup/core/_hub_crud.py
tests/hub-local/test_all.py

- https://github.com/laminlabs/laminapp-ui/pull/545

♻️ More fine-grained db credentials management

---

docs/hub-cloud/05-init-hosted-instance.ipynb
docs/hub-cloud/06-connect-hosted-instance.ipynb
lamindb_setup/core/upath.py

trying to fix https://github.com/laminlabs/lamindb-setup/issues/697

🐛 Fix directory uploads for hosted instances

---

lamindb_setup/core/django.py

@Koncopd isn't it prettier like so?

♻️ Refactor clean up

---

lamindb_setup/core/types.py

- https://github.com/laminlabs/lnschema-core/pull/363

♻️ Replace TypeVar with TypeAlias

---

lamindb_setup/core/_hub_client.py
lamindb_setup/core/_hub_core.py
tests/hub-local/test_all.py
tests/hub-prod/test_switch_and_fallback_env.py

Fixes:
- https://github.com/laminlabs/lamindb-setup/issues/714

🚸 Refresh token also upon access-aws

---

lamindb_setup/_connect_instance.py
lamindb_setup/core/_settings_instance.py
lamindb_setup/core/_settings_storage.py

https://www.notion.so/laminlabs/Data-sharing-through-hybrid-local-remote-LaminDB-instances-e01025ed0e3e4f06948c4390894f20a8

✨ Enable hybrid storage mode

---

lamindb_setup/_connect_instance.py
tests/hub-cloud/test_connect_instance.py

Address:
- https://github.com/laminlabs/lamindb-setup/issues/719

♻️ Do not always read from local cache

---

docs/hub-cloud/01-init-on-prem-instance.ipynb
docs/hub-cloud/02-connect-on-prem-instance.ipynb
lamindb_setup/_connect_instance.py
lamindb_setup/_delete.py
lamindb_setup/core/_hub_core.py
lamindb_setup/core/_settings_storage.py
lamindb_setup/core/upath.py
tests/hub-cloud/test_connect_instance.py
tests/hub-cloud/test_init_instance.py
tests/hub-prod/conftest.py

Deletes instances on the hub and adds an additional check.
This still doesn't delete remote postgres instances.

🚸 In `.delete()`, check for data deletion & delete from hub

---

docs/hub-cloud/05-init-hosted-instance.ipynb
docs/hub-cloud/06-connect-hosted-instance.ipynb
lamindb_setup/_connect_instance.py

Fixing test failures due to https://github.com/laminlabs/lamindb-setup/commit/145251043dec811f8409ec4c7cb08c931a707300

🐛 Fix test failures

---

lamindb_setup/_connect_instance.py
lamindb_setup/_delete.py
lamindb_setup/core/_settings_instance.py
tests/hub-prod/conftest.py

♻️ Refactor delete & connect

---

lamindb_setup/core/hashing.py

improves the speed by a factor of ~1.5-2

⚡️ Speed-up file hash

---

.pre-commit-config.yaml
docs/hub-cloud/06-connect-hosted-instance.ipynb
lamindb_setup/core/upath.py
tests/storage/test_storage_stats.py

- https://github.com/laminlabs/lamindb/pull/1677

🚸 Make `upload_from()`, `download_to()`, and `view_tree()` more user friendly

---

lamindb_setup/_register_instance.py
tests/hub-local/test_update_schema_in_hub.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1719411458764669?thread_ts=1719406068.357659&cid=C04FPE8V01W

💚 Fix test

---

lamindb_setup/core/_private_django_api.py

🐛 Fix private_django_api encoding on Windows

---

lamindb_setup/_schema_metadata.py

- https://github.com/laminlabs/lnschema-core/pull/414

🚚 Rename `RecordMeta` to `Registry`

---

lamindb_setup/core/_hub_core.py
lamindb_setup/core/_hub_crud.py

https://github.com/laminlabs/laminhub/issues/1008

♻️ Query the default storage on connecting an instance

---

lamindb_setup/core/_hub_core.py
lamindb_setup/core/_settings_storage.py

https://laminlabs.slack.com/archives/C07DB677JF6/p1723656079519069?thread_ts=1723618378.437019&cid=C07DB677JF6

🐛 Do not delete existing storage records in hub on failed inits

---

lamindb_setup/_init_instance.py
lamindb_setup/_set_managed_storage.py
lamindb_setup/core/_settings_instance.py
lamindb_setup/core/_settings_storage.py
tests/hub-local/test_all.py

https://laminlabs.slack.com/archives/C07DB677JF6/p1723623568991179?thread_ts=1723618378.437019&cid=C07DB677JF6

🐛 Make `set_managed_storage()` safer

---

docs/hub-cloud/07-keep-artifacts-local.ipynb

Fixes https://github.com/laminlabs/lamindb-setup/issues/752

✅ Disentangle 07-keep-artifacts-local for prod and staging

---

lamindb_setup/_delete.py

Fix https://github.com/laminlabs/lamindb-setup/issues/858 https://github.com/laminlabs/lamindb-setup/issues/686

🐛 Delete only root folder in cache on instance delete

---

docs/hub-prod/test-cache-management.ipynb
docs/hub-prod/test-cloud-sync.ipynb
lamindb_setup/_cache.py
lamindb_setup/_delete.py
lamindb_setup/core/_settings.py
lamindb_setup/core/_settings_load.py
lamindb_setup/core/_settings_save.py
lamindb_setup/core/_settings_storage.py

Fix https://github.com/laminlabs/lamindb-setup/issues/620

♻️ Move settings.storage.cache_dir to settings.cache_dir

---

lamindb_setup/_init_instance.py
lamindb_setup/core/_settings_storage.py
tests/hub-cloud/test_init_instance.py

Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/18

🚸 Raise SystemExit on storage=None in init

---

docs/hub-cloud/02-connect-local-instance.ipynb
docs/hub-cloud/08-test-multi-session.ipynb
lamindb_setup/_connect_instance.py
lamindb_setup/_init_instance.py
noxfile.py
tests/hub-cloud/test_edge_request.py

Resolves: https://github.com/laminlabs/pfizer-lamin-usage/issues/53

🚸 Clearer feedback when somebody tries to switch the default instance

---

lamindb_setup/core/_hub_client.py
tests/hub-local/test_all.py

Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/34

✨ Overwrite access_token after renewal

---

lamindb_setup/core/_settings.py

Fix https://github.com/laminlabs/lamindb-setup/issues/894

📝 Fix docs for settings

---

lamindb_setup/core/hashing.py
lamindb_setup/core/upath.py
tests/storage/test_storage_stats.py

Closes https://github.com/laminlabs/lamindb-setup/issues/748

✨ Compute hash for files in Google Cloud Storage and Hugging Face

---

lamindb_setup/core/upath.py

Came up today.
https://cran.r-project.org/web/packages/qs/vignettes/vignette.html

🍱 Add `.qs` file as a valid simple suffix

---

lamindb_setup/core/_setup_bionty_sources.py

Context:
- https://github.com/laminlabs/lamindb/pull/2207
With:
- https://github.com/laminlabs/bionty/pull/171

♻️ Refactor setup bionty sources

---

lamindb_setup/core/_deprecated.py
noxfile.py

Jointly with:
- https://github.com/laminlabs/lndocs/pull/112

🎨 Polish the deprecated decorator

---

lamindb_setup/_check_setup.py
lamindb_setup/_migrate.py

For context https://github.com/laminlabs/lamindb-setup/pull/941

🩹 migrate without setting auto-connect to False

---

pyproject.toml

See https://github.com/supabase/storage-py/issues/343

⬆️ Remove upper bound on storage3

---

lamindb_setup/core/_hub_core.py

Close https://github.com/laminlabs/lamindb-setup/issues/952

🔊 Change init message for local and sqlite instances

---

docs/hub-prod/test-connect-anonymously-set-token.ipynb
lamindb_setup/_connect_instance.py
lamindb_setup/core/_hub_client.py
lamindb_setup/core/_hub_core.py
lamindb_setup/core/django.py
noxfile.py
tests/hub-local/scripts/script-connect-fine-grained-access.py
tests/hub-local/test_all.py

Allows to connect to instances with fine-grained-permissions.

✨ Request a db token for instances with fine-grained permissions

---

lamindb_setup/_connect_instance.py
lamindb_setup/core/_settings_instance.py
lamindb_setup/core/_settings_load.py
lamindb_setup/core/_settings_save.py
lamindb_setup/core/_settings_store.py
lamindb_setup/core/django.py
tests/hub-local/scripts/script-connect-fine-grained-access.py

Internal, needed for fine-grained permissions.

✨ Write and use db_permissions

---

docs/hub-cloud/04-test-bionty.ipynb
lamindb_setup/_close.py
lamindb_setup/core/_setup_bionty_sources.py

Requires: https://github.com/laminlabs/bionty/pull/217

♻️ Remove source yamls in bionty

---

.gitignore
docs/hub-cloud/03-add-managed-storage.ipynb
docs/hub-cloud/07-keep-artifacts-local.ipynb
lamindb_setup/core/_settings_instance.py
lamindb_setup/core/_settings_storage.py
lamindb_setup/core/upath.py

Running tests in lamindb here:
- https://github.com/laminlabs/lamindb/pull/2580

🚚 Rename `_is_initialized` to `storage_uid.txt`

---

lamindb_setup/_init_instance.py

- https://github.com/laminlabs/lamin-cli/pull/122

♻️ Default to current working directory during lamin init

---

lamindb_setup/core/upath.py

The problem is described here https://github.com/fsspec/s3fs/issues/897
https://laminlabs.slack.com/archives/C04FPE8V01W/p1742917635634669
https://laminlabs.slack.com/archives/C04FPE8V01W/p1739260657718099

⚡️ Make upload of large directories more robust by reducing batch size

---

pyproject.toml

⬇️ Add upper bound on gotrue

---

docs/hub-prod/test-connect-anonymously-set-token.ipynb
lamindb_setup/core/_hub_core.py
lamindb_setup/core/django.py
noxfile.py
tests/hub-local/scripts/script-connect-fine-grained-access.py
tests/hub-local/test_all.py

Paired with:
- https://github.com/laminlabs/lamindb/pull/2641

🐛 Set db token only on the transaction level

---

lamindb_setup/core/upath.py

`.pt` and `.ckpt` for model weights/checkpoints

✨ Add `.pt` and `.ckpt` to valid suffixes

---

docs/hub-prod/test-connect-anonymously.ipynb
lamindb_setup/core/_settings_user.py
lamindb_setup/core/django.py
tests/hub-local/scripts/script-connect-fine-grained-access.py

This PR allows to refresh expired db tokens (jwt) for instances with fine-grained access.

✨ Refresh db token on expiration

---

.github/workflows/build.yml
tests/hub-local/scripts/script-connect-fine-grained-access.py

https://github.com/laminlabs/laminhub/pull/2388

✅ Temp table based authentication (adapt tests)

---

.github/workflows/build.yml
tests/hub-local/scripts/script-connect-fine-grained-access.py

https://github.com/laminlabs/laminhub/pull/2403

✅ Test auth errors

---

lamindb_setup/core/_hub_core.py
tests/hub-local/test_all.py

This is needed to check for parents in central in `lamindb`.
Relies on https://github.com/laminlabs/laminhub/pull/2476

✨ Implement `select_storage_or_parent`

---

lamindb_setup/_connect_instance.py
tests/hub-cloud/test_connect_instance.py

💚 Fix CI due to enabling fine-grained access on lamindata

---

.github/workflows/build.yml
tests/hub-local/test_all.py

https://github.com/laminlabs/laminhub/pull/2491

✅ Fix hub-local tests for "Make organization members independent from teams"

---

lamindb_setup/__init__.py
lamindb_setup/_check_setup.py
lamindb_setup/_connect_instance.py
lamindb_setup/_init_instance.py
lamindb_setup/core/_settings_load.py
lamindb_setup/core/cloud_sqlite_locker.py
lamindb_setup/core/exceptions.py
lamindb_setup/errors.py

♻️ Define all exceptions in `lamindb_setup.errors`

---

lamindb_setup/_schema_metadata.py
lamindb_setup/core/django.py
lamindb_setup/core/upath.py

Adds debugging logs for side-effects

🔊 Log side-effects

---

docs/hub-cloud/05-init-hosted-instance.ipynb
docs/hub-cloud/06-connect-hosted-instance.ipynb
docs/hub-cloud/07-keep-artifacts-local.ipynb
lamindb_setup/_init_instance.py
lamindb_setup/_register_instance.py
lamindb_setup/_set_managed_storage.py
lamindb_setup/core/_hub_core.py
lamindb_setup/core/_settings_storage.py
lamindb_setup/core/upath.py
lamindb_setup/errors.py

- https://github.com/laminlabs/lamindb/pull/2839

♻️ Refactor storage deletion

---

lamindb_setup/core/_hub_core.py
lamindb_setup/core/_settings_storage.py

For:
- https://github.com/laminlabs/lamindb/pull/2841

♻️ Simplify storage marking & storage-from-hub retrieval

---

tests/hub-local/scripts/script-connect-fine-grained-access.py

https://github.com/laminlabs/laminhub/pull/2726

✅ Adapt local-hub tests to caching RLS

---

docs/hub-cloud/08-test-multi-session.ipynb
lamindb_setup/_connect_instance.py
lamindb_setup/_init_instance.py

Merges the original PR into the `alwaysconnect` branch rather than into the main branch.
- https://github.com/laminlabs/lamindb-setup/pull/1046

✨ Allow re-connecting through re-configuring Django in the same Python process

---

lamindb_setup/core/_settings.py
tests/hub-prod/test_global_settings.py

For:
- https://github.com/laminlabs/lamindb/pull/2909

✨ Add a branch and a space setting

---

lamindb_setup/core/_settings.py
lamindb_setup/core/_settings_instance.py
lamindb_setup/core/_settings_user.py

💄 Prettify settings display

---

lamindb_setup/core/_settings.py

Try to avoid importing models from `lamindb` as much as possible.

⚡️ Avoid importing `lamindb` in `settings.__repr__`

---

docs/hub-cloud/07-keep-artifacts-local.ipynb
lamindb_setup/core/_settings_instance.py

Slack thread: https://laminlabs.slack.com/archives/C04FPE8V01W/p1752839178788209

🚸 Improve UX of keep-artifacts-local mode

---

lamindb_setup/core/_aws_options.py
lamindb_setup/core/_hub_core.py

Fix https://github.com/laminlabs/lamindb/issues/2936

✨ Allow `access_aws` with anonymous users

---

lamindb_setup/core/_settings_instance.py

Address:
- https://github.com/laminlabs/lamindb-setup/issues/1108

🐛 Fix auto-search for corrupted local storage location

---

lamindb_setup/core/_aws_options.py
lamindb_setup/core/_hub_core.py
noxfile.py
tests/hub-local/scripts/script-connect-fine-grained-access.py

Requires https://github.com/laminlabs/laminhub/pull/3087

✨ Allow to receive and add extra parameters for managed buckets

---

lamindb_setup/core/upath.py
noxfile.py

https://github.com/huggingface/huggingface_hub/issues/3263#issuecomment-3118383930

👽️ Adapt huggingface sync to the changes in the API

---

lamindb_setup/_migrate.py
lamindb_setup/core/django.py

- https://github.com/laminlabs/lamin-cli/pull/148

✨ Enable reverting database migrations

---

tests/hub-local/test_all.py

Adapt `hub-local` to https://github.com/laminlabs/laminhub/pull/3290

💚 Adapt `hub-local`

---

docs/hub-cloud/03-add-managed-storage.ipynb
tests/hub-cloud/scripts/script-init-pass-user-no-writes.py

this commit was pushed to main by mistake https://github.com/laminlabs/lamindb-setup/commit/cdd7ee224f16a19f0a3102a881050284ebdc905d

✅ Adapt testing adding managed storage for new hub API
